### PR TITLE
Fix/user independence

### PR DESCRIPTION
**Pull request by Vertonowsky**
Since users can have the same name in different rooms, we should be strict when overriding `.equals()` method. Removed `name` property from equals() method, so when it is used, it won't cause problems.

### CODE REVIEW

**Review by kestivvi — COMMENTED** [review]
Very good, but why do you include the documentation from the #103 pr as well? XDDDDDD

Ok, let then merge the #103 pr first, then this one. XD

Resolve merge conflicts in this one after the #103 will be merged.

**Review by KamilDevelopments — DISMISSED** [review]

**Review by agatamrnw — COMMENTED** [review]
It's good but the conflict between files should be solved

**Comment by Vertonowsky** [comment]
XD I should've changed my branch to develop before pushing this one commit XD Well, i'll fix it. Firstly I'll merge previous PR and then i'll fix this one

**Review by kestivvi — DISMISSED** [review]

**Review by agatamrnw — DISMISSED** [review]

**Review by kestivvi — APPROVED** [review]

**Review by Antonidass5 — APPROVED** [review]
good job bro 🐛 🔫

**Pull request merged**
