### PR TITLE
Unit Tests to JsonParser Class

### LINKED ISSUE #52: Add Unit Tests to JsonParser Class
As the manager, I have noticed that the `JsonParser` class lacks unit tests. This is a critical issue as it can lead to unexpected behavior and bugs in the application. Without proper testing, it is difficult to ensure that the class is functioning as intended and that any changes made to it do not break existing functionality.

I recommend that we create unit tests for the `JsonParser` class to ensure that it is working as expected. These tests should cover all possible scenarios, including valid and invalid JSON strings, missing fields, and optional fields. By doing so, we can catch any issues early on and ensure that the class is functioning as intended.

Technical Details:
The `JsonParser` class is responsible for parsing JSON strings into Java objects. It uses the `Gson` library to parse the JSON string into a `JsonObject` and then checks if all required fields are present in the `JsonObject`. If any required fields are missing, it throws a `JsonMissingFieldException`. Finally, it parses the `JsonObject` into an object of the specified class using the `Gson` library again.

To create unit tests for this class, we can use a testing framework `JUnit`. We should create tests that cover all possible scenarios, including valid and invalid JSON strings, missing fields, and optional fields. We can create new nested classes for testing purposes and parse JSON strings on them to ensure that the `JsonParser` class is functioning correctly. These nested classes can cover different scenarios and edge cases to ensure that the class is handling them correctly.

For advanced:
We can also use mock objects to simulate different scenarios and ensure that the class is handling them correctly.

### PR DESCRIPTION
**Pull request by s210897**
JsonParser class unit test. All tests passed, but there are still a few more tests to add.

### CODE REVIEW

**Review by kestivvi — CHANGES_REQUESTED** [review]
Please, add `*.iml` files to `.gitignore` and delete them from this branch. These files get changed all the time when it has nothing to do with the code. They are the local configuration files for IDEAs.

**Review by agatamrnw — DISMISSED** [review]

**Comment by kestivvi** [comment]
Great 🎉🎊🎈, do you want to improve on this unit test class? Or merge it to develop as it is and then somebody (or you) would finish it up? @s210897

**Comment by s210897** [comment]
I want to merge this unit test class for now and update and expand it in the future   @kestivvi

**Review by kestivvi — APPROVED** [review]
✨🎈🎊🎉🎉🎉🎉

**Review by agatamrnw — APPROVED** [review]

**Pull request merged**
